---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:seanag0234/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image: seanag/flux-test:1.0.4
    replicaCount: 3
